//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class администрация
    {
        public int id { get; set; }
        public string администратор { get; set; }
        public string должность { get; set; }
        public string контакты { get; set; }
        public Nullable<int> id_модуля { get; set; }
    
        public virtual МодулиСтанции МодулиСтанции { get; set; }
    }
}
