//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class АрхивСтанции
    {
        public АрхивСтанции()
        {
            this.РезервныеКопии = new HashSet<РезервныеКопии>();
        }
    
        public int ID_записи { get; set; }
        public string Событие { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Описание { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual ICollection<РезервныеКопии> РезервныеКопии { get; set; }
    }
}
