//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class ГрузовыеМиссии
    {
        public int id { get; set; }
        public string поставщик { get; set; }
        public Nullable<System.DateTime> дата_доставки { get; set; }
        public string содержимое { get; set; }
        public Nullable<int> модуль_id { get; set; }
    
        public virtual МодулиСтанции МодулиСтанции { get; set; }
    }
}
