//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class ГрафикСмен
    {
        public int ID_смены { get; set; }
        public Nullable<int> ID_космонавта { get; set; }
        public Nullable<System.DateTime> ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
    
        public virtual Космонавты Космонавты { get; set; }
    }
}
