//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class инженеры
    {
        public инженеры()
        {
            this.технические_неисправности = new HashSet<технические_неисправности>();
            this.ТехническоеОбслуживание = new HashSet<ТехническоеОбслуживание>();
        }
    
        public int id { get; set; }
        public string ФИО { get; set; }
        public string отдел { get; set; }
        public string квалификация { get; set; }
        public Nullable<int> опыт { get; set; }
        public string телефон { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<технические_неисправности> технические_неисправности { get; set; }
        public virtual ICollection<ТехническоеОбслуживание> ТехническоеОбслуживание { get; set; }
    }
}
