//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Космонавты
    {
        public Космонавты()
        {
            this.ГрафикСмен = new HashSet<ГрафикСмен>();
            this.Командировки = new HashSet<Командировки>();
            this.медицинские_данные = new HashSet<медицинские_данные>();
            this.РасписаниЕРабот = new HashSet<РасписаниЕРабот>();
        }
    
        public int id { get; set; }
        public string ФИО { get; set; }
        public string должность { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
        public string статус { get; set; }
        public string Фото { get; set; }
    
        public virtual ICollection<ГрафикСмен> ГрафикСмен { get; set; }
        public virtual ICollection<Командировки> Командировки { get; set; }
        public virtual ICollection<медицинские_данные> медицинские_данные { get; set; }
        public virtual ICollection<РасписаниЕРабот> РасписаниЕРабот { get; set; }
    }
}
