//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class медицинские_данные
    {
        public медицинские_данные()
        {
            this.РезервныеКопии = new HashSet<РезервныеКопии>();
        }
    
        public int id { get; set; }
        public Nullable<int> ID_космонавт { get; set; }
        public Nullable<System.DateTime> обследование { get; set; }
        public Nullable<int> давление { get; set; }
        public Nullable<int> пульс { get; set; }
        public Nullable<int> уровень_сахара { get; set; }
        public string заключение { get; set; }
    
        public virtual Космонавты Космонавты { get; set; }
        public virtual ICollection<РезервныеКопии> РезервныеКопии { get; set; }
    }
}
