//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class МодулиСтанции
    {
        public МодулиСтанции()
        {
            this.администрация = new HashSet<администрация>();
            this.Видеонаблюдение = new HashSet<Видеонаблюдение>();
            this.ГрузовыеМиссии = new HashSet<ГрузовыеМиссии>();
            this.оборудование = new HashSet<оборудование>();
            this.Расходы = new HashSet<Расходы>();
            this.технические_неисправности = new HashSet<технические_неисправности>();
            this.ТехническоеОбслуживание = new HashSet<ТехническоеОбслуживание>();
        }
    
        public int id { get; set; }
        public string название { get; set; }
        public string назначение { get; set; }
        public Nullable<System.DateTime> дата_запуска { get; set; }
        public string состояние { get; set; }
        public Nullable<int> id_экипажа { get; set; }
    
        public virtual ICollection<администрация> администрация { get; set; }
        public virtual ICollection<Видеонаблюдение> Видеонаблюдение { get; set; }
        public virtual ICollection<ГрузовыеМиссии> ГрузовыеМиссии { get; set; }
        public virtual экипажи экипажи { get; set; }
        public virtual ICollection<оборудование> оборудование { get; set; }
        public virtual ICollection<Расходы> Расходы { get; set; }
        public virtual ICollection<технические_неисправности> технические_неисправности { get; set; }
        public virtual ICollection<ТехническоеОбслуживание> ТехническоеОбслуживание { get; set; }
    }
}
