//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class оборудование
    {
        public int id { get; set; }
        public string серийный_номер { get; set; }
        public string производитель { get; set; }
        public string характеристики { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<System.DateTime> дата_установки { get; set; }
        public Nullable<int> ID_модуля { get; set; }
    
        public virtual МодулиСтанции МодулиСтанции { get; set; }
    }
}
