//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class РасписаниЕРабот
    {
        public int id { get; set; }
        public string задача { get; set; }
        public Nullable<int> id_Космонавта { get; set; }
        public Nullable<System.DateTime> срок { get; set; }
    
        public virtual Космонавты Космонавты { get; set; }
    }
}
